resources:
- repo: self
  fetchDepth: 1
trigger:
- main
- develop

variables:
  TargetFramework: 'net6.0'
  BuildConfiguration: 'Release'
  DockerImageName: 'rpm-2023/rpmapp/rpmapi'
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    latestTag: "latest"
    tag: '$(Build.SourceBranchName)-$(Build.BuildId)'
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    latestTag: "develop"
    tag: '$(Build.SourceBranchName)-$(Build.BuildId)'

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: $(System.DefaultWorkingDirectory)
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'rpm_container'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: 'Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'
    tags: |
      $(latestTag)
      $(tag)
