resources:
- repo: self
  fetchDepth: 1
trigger:
- master
variables:
  TargetFramework: 'net6.0'
  BuildConfiguration: 'Release'
  DockerImageName: 'asia-northeast3-docker.pkg.dev/rpm-2023/rpmapp/api'
  latestTag: "latest"
  tag: '$(Build.SourceBranchName)-$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'rpm_container'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: 'Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'
    tags: |
      $(latestTag)
      $(tag)