// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RPM.Domain.Models;

[Table("Instance_Snapshot")]
public partial class InstanceSnapshot
{
    [Key]
    [Column("SNo")]
    public long Sno { get; set; }

    [StringLength(6)]
    public string SnapshotMonth { get; set; } = null!;

    public long InstId { get; set; }

    public long AccountId { get; set; }

    public long CredId { get; set; }

    [StringLength(7)]
    public string Vendor { get; set; } = null!;

    [StringLength(200)]
    public string ResourceId { get; set; } = null!;

    public bool IsEnable { get; set; }

    [StringLength(200)]
    public string? Name { get; set; }

    [StringLength(200)]
    public string? Region { get; set; }

    [StringLength(200)]
    public string? Type { get; set; }

    [StringLength(4000)]
    public string? Tags { get; set; }

    public string? Info { get; set; }

    [StringLength(1000)]
    public string? Note { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SavedAt { get; set; }

    [StringLength(50)]
    public string? SaverId { get; set; }
}